all:
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
### Para Rhaap el inventario no debe tener ni usuario ni credenciales ya que las configuramos desde el propio aap    
#   ansible_user: ubuntu
#   ansible_ssh_private_key_file: /home/juanma/.ssh/id_rsa

  children:
    proxy:
      hosts:
        server1:
          ansible_host: 192.168.122.35
    webservers:
      hosts:
        server2:
          ansible_host: 192.168.122.165
    dbservers:
      hosts:
        server3:
          ansible_host: 192.168.122.28
    wordpress:
      hosts:
        server2:
          ansible_host: 192.168.122.165
