---
# site.yml
- hosts: dbservers
  become: true
  roles:
    - jpaybar.Mysql

- hosts: webservers
  become: true
  roles:
    - jpaybar.Apache2
    - jpaybar.Php-fpm

- hosts: wordpress
  become: true
  roles:
    - jpaybar.Wordpress

- hosts: proxy
  become: true
  roles:
    - jpaybar.Nginx_Proxy