---
# site.yml
- hosts: dbservers
  become: true
  roles:
    - ../Roles/jpaybar.Mysql

- hosts: webservers
  become: true
  roles:
    - ../Roles/jpaybar.Apache2
    - ../Roles/jpaybar.Php-fpm

- hosts: wordpress
  become: true
  roles:
    - ../Roles/jpaybar.Wordpress

- hosts: proxy
  become: true
  roles:
    - ../Roles/jpaybar.Nginx_Proxy