---
# tasks file for jpaybar.Apache2

#############################################################################################################################
# Getting information about useful variables on remote hosts:
#
# ansible all -i "inventory.yml" -l "select_from_inventory" -m "setup" -u "user" -k "ssh_passwd" | grep "ansible_facts['distribution']"
#
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
#############################################################################################################################

- name: Load OS specific variables
  include_tasks: variables.yml

- name: Install Apache2 if Ubuntu distribution
  include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == "Ubuntu" and
        ansible_facts['distribution_version'] in ["18.04", "20.04", "22.04", "24.04"]