---
  
- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_facts['distribution'] | lower }}_vars.yml"
    #- "{{ ansible_facts['distribution'] | lower }}_config.yml"
