#SPDX-License-Identifier: MIT-0
---
# handlers file for jpaybar.Common
# Los handlers se ejecutan al final del play solo si fueron notificados
# y solo una vez aunque hayan sido notificados varias veces

# =============================================================================
# NTP
# =============================================================================

- name: restart chrony
  ansible.builtin.service:
    name: chronyd
    state: restarted

# =============================================================================
# NFS
# =============================================================================

- name: remount nfs
  ansible.builtin.command: mount -a -t nfs
  changed_when: false
