---
# vars file for jpaybar.Apache2

install_packages:
  - apache2
  - openssl

apache_mods:
  - ssl
  - headers
  - rewrite

apache_cert_path: "/etc/ssl/certs/apache.crt"
apache_key_path: "/etc/ssl/private/apache.key"
