---
# defaults file for jpaybar.Mysql

# MySQL user
mysql_user_name: test
mysql_user_password: test

# MySQL root user
mysql_root_username: root
mysql_root_password: root

# MySQL settings.
mysql_port: "3306"
mysql_bind_address: '0.0.0.0'
mysql_datadir: /var/lib/mysql





