---
# tasks file for jpaybar.Php-fpm

##==========================##
## Variables configuration. ##
##=========================================================================================================================##
- name: Variables files
  include_tasks: variables.yml
##=========================================================================================================================##

##==========================##
## Setup/Install tasks      ##
##=========================================================================================================================##
- name: Install php-fmp if Ubuntu distribution
  include_tasks: ubuntu.yml
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "18.04") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "20.04") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "22.04") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "24.04") 
##=========================================================================================================================##  



