---
# tasks file for jpaybar.Mysql
    
- name: Install epel-release for extra packages
  yum:
    name: epel-release
    state: present    
    
- name: Install MySQL
  yum:
    name: "{{ mysql_packages }}"
    state: present
    
- name: Enable and start MySQL on boot.
  service: "name={{ mysql_daemon }} state=started enabled={{ mysql_enabled_on_startup }}"
  
- name: Install MySQL-python on Centos 7.9
  yum:
    name: MySQL-python
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version'] == "7.9")
  
- name: Install python3-mysqlclient on Centos 8.5
  yum:
    name: python3-mysqlclient
    state: present
  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_version'] == "8.5")
    
- name: Set MySQL root password and privileges  
  mysql_user:  
    name: "{{ mysql_root_username }}"  
    host: "{{ item }}"  
    password: "{{ mysql_root_password }}"  
    login_user: "{{ mysql_root_username }}"  
    login_password: "{{ mysql_root_password }}"  
    login_unix_socket: /var/lib/mysql/mysql.sock
    check_implicit_admin: yes  
    priv: "*.*:ALL,GRANT"  
  with_items:  
  - "{{ ansible_hostname }}"  
  - 127.0.0.1  
  - ::1  
  - localhost
  - 192.168.10.20 ###=== Allow remote connection to user "root" from this IP ===###
                  ###=== The "bind-address" parameter must also be modified  ===###
                  ###=== in the MySQL global configuration file to allow remote connections ===###
  
- name: Copy global MySQL configuration template.
  template:
    src: "{{ mysql_template_config }}"
    dest: "{{ mysql_config_file }}"
  notify: restart mysql