---
# tasks file for jpaybar.Mysql

- name: Create database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present
    login_user: "{{ mysql_root_username }}"
    login_password: "{{ mysql_root_password }}"
  tags: Create_database

