---
# tasks file for jpaybar.Mysql

- name: Create dbname database  
  mysql_db: 
    name: dbname 
    state: present 
    login_user: "{{ mysql_root_username }}" 
    login_password: "{{ mysql_root_password }}"  
    
- name: Copy sql script  
  copy: 
    src: dbname.sql 
    dest: /tmp/dbname.sql  
    
- name: Insert sample data (films table) into database  
  mysql_db: 
    name: dbname 
    state: import 
    target: /tmp/dbname.sql 
    login_user: "{{ mysql_root_username }}" 
    login_password: "{{ mysql_root_password }}"