---
# tasks file for jpaybar.Mysql

- name: Install MySQL and pip packages 
  apt:
    name: "{{ mysql_packages }}"
    update_cache: yes
    state: present
    
- name: Make sure pymysql is present
  pip:
    name: pymysql
    state: present
    
- name: Set MySQL root password and privileges 
  mysql_user:  
    name: "{{ mysql_root_username }}"  
    host: "{{ item }}"  
    password: "{{ mysql_root_password }}"  
    login_user: "{{ mysql_root_username }}"  
    login_password: "{{ mysql_root_password }}"  
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: yes  
    priv: "*.*:ALL,GRANT"  
  with_items:
  - "{{ ansible_hostname }}"  
  - 127.0.0.1  
  - ::1  
  - localhost
  - 192.168.10.20 ###=== Allow remote connection to user "root" from this IP ===###
                  ###=== The "bind-address" parameter must also be modified  ===###
                  ###=== in the MySQL global configuration file to allow remote connections ===###

- name: Copy global MySQL configuration template.
  template:
    src: "{{ mysql_template_config }}"
    dest: "{{ mysql_config_file }}"
  notify: restart mysql