---
# tasks file for jpaybar.Mysql

#############################################################################################################################
# Getting information about useful variables on remote hosts:
#
# ansible all -i "inventory.yml" -l "select_from_inventory" -m "setup" -u "user" -k "ssh_passwd" | grep "ansible_facts['distribution']"
#
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/setup_module.html
#############################################################################################################################

##==========================##
## Variables configuration  ##
##=========================================================================================================================##
- name: Variables files
  include_tasks: variables.yml
##=========================================================================================================================##

##==========================##
## Setup/Install tasks      ##
##=========================================================================================================================##
- name: Install MySQL if Ubuntu distribution
  include_tasks: ubuntu.yml
  when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "18.04") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "20.04") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "22.04") or
        (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version'] == "24.04") 
##=========================================================================================================================##        

##==========================##
## MySQL users              ##
##=========================================================================================================================##
- name: MySQL users
  include_tasks: users.yml
##=========================================================================================================================##

##==========================##
## Databases                ##
##=========================================================================================================================##
- name: Create databases
  include_tasks: databases.yml
##=========================================================================================================================##