---
# vars file for jpaybar.Mysql

#============================== OS VARIABLES ====================================
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_facts['distribution'] | lower }}_vars.yml"
    #- "{{ ansible_facts['distribution'] | lower }}_config.yml"
#================================================================================

#======================= mysqld.cnf VERSIONS FOR UBUNTU =========================
- name: Include mysqld.cnf version for Ubuntu 18.04
  include_vars: ubuntu_1804_mysqld.cnf_version.yml
  when: ansible_facts['distribution_version'] == "18.04"
 
- name: Include mysqld.cnf version for Ubuntu 20.04
  include_vars: ubuntu_2004_mysqld.cnf_version.yml
  when: ansible_facts['distribution_version'] == "20.04"
  
- name: Include mysqld.cnf version for Ubuntu 22.04
  include_vars: ubuntu_2204_mysqld.cnf_version.yml
  when: ansible_facts['distribution_version'] == "22.04"
  
- name: Include mysqld.cnf version for Ubuntu 24.04
  include_vars: ubuntu_2404_mysqld.cnf_version.yml
  when: ansible_facts['distribution_version'] == "24.04"
#================================================================================
